version: 2.1

commands:
  protoc_install:
    parameters:
      version:
        type: string
        default: "3.11.4"
    steps:
      - run:
          name: Install protoc
          command: |
            PB_REL="https://github.com/protocolbuffers/protobuf/releases"
            curl -LO $PB_REL/download/v<< parameters.version >>/protoc-<< parameters.version >>-linux-x86_64.zip
            unzip protoc-<< parameters.version >>-linux-x86_64.zip -d $HOME/.local
  verify_clean:
    steps:
      - run:
          name: Verify if all files are clean
          command: |
            git diff --exit-code


jobs:
  python-gen:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout

      - protoc_install
      - run:
          name: Generate contract from proto
          command: |
            pip3 install grpcio-tools

            make proto-python
      - verify_clean

  go-gen:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout

      - protoc_install
      - run:
          name: Generate contract from proto
          command: |
            go get github.com/golang/protobuf/protoc-gen-go

            make proto-go
      - verify_clean

  buf-lint:
    docker:
      - image: bufbuild/buf:0.11.0
    steps:
      - checkout

      - run:
          name: Buf lint
          command: |
            buf check lint

workflows:
  test:
    jobs:
      - python-gen
      - go-gen
      - buf-lint
